#!/bin/sh

riverctl default-attach-mode below
riverctl focus-follows-cursor disabled
riverctl hide-cursor timeout 1000
riverctl set-cursor-warp on-output-change
riverctl set-repeat 40 300

riverctl keyboard-layout -model "keyboard*" hu
riverctl input "pointer-1267-12608-ELAN0001:00_04F3:3140_Touchpad" natural-scroll enabled
riverctl input "pointer-1267-12608-ELAN0001:00_04F3:3140_Touchpad" tap enabled

riverctl map normal Super Return spawn foot
riverctl map normal Super B spawn firefox-developer-edition
riverctl map normal Super R spawn 'bemenu-run -i  -p "run:" -C --fn "Hack Nerd Font 13" --nb "#11111b" --tb "#11111b" --hb "#f5c2e7" --fb "#11111b" --tf "#f5c2e7" --hf "#11111b" --ab "#11111b" --hp 10'
riverctl map normal None Print spawn "pkill slurp || slurp | grim -g - - | wl-copy"

riverctl map normal Super Q close

riverctl map normal Super+Shift E exit
riverctl map normal Super period spawn "systemctl suspend"

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift Return zoom
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super+Shift Space toggle-float

riverctl map normal Super F toggle-fullscreen

riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_SINK@ toggle"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_SINK@ 5%-"
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_SINK@ 5%+"

riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set +5%'

riverctl background-color 0xF5C2E7
riverctl border-color-focused 0xF5C2E7
riverctl border-color-unfocused 0x11111b
riverctl border-width 3
riverctl rule-add -app-id 'firefox*' ssd
riverctl rule-add -app-id 'libreoffice*' ssd

riverctl default-layout rivertile
riverctl spawn "rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.55"

# riverctl spawn "swaybg -i ~/Pictures/Wallpapers/ocean.png -o eDP-1"
riverctl spawn "yambar"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river:wlroots"
