edition = "2021"
newline_style = "Unix"
max_width = 80
comment_width = 80
reorder_imports = true
reorder_impl_items = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
normalize_comments = true
