primary: &primary F5C2E7FF

bar:
  height: 22
  spacing: 10
  margin: 5
  location: top
  font: Hack Nerd Font:style=Bold:size=14:antialiasing=true
  foreground: CDD6F4FF
  background: 11111BFF
  left:
    - river:
        content:
          map:
            conditions:
              ~occupied: {empty: {}}
              occupied:
                - map:
                    conditions:
                      state == "focused":
                        string: {text: "{id}", foreground: *primary, margin: 5, font: Hack Nerd Font:style=Bold:size=16:antialiasing=true}
                      state == "invisible":
                        string: {text: "{id}", margin: 5}
                      id == "default":
                        string: {text: ""}
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}"}
  right:
    - disk-io:
        poll-interval: 1000
        content:
          map:
            conditions:
              device == Total:
                - string: {text: "󱛟 ", foreground: *primary}
                - string: {text: "I: {read_speed:mb} MB/s, "}
                - string: {text: "O: {write_speed:mb} MB/s "}
                - string: {text: "I/Os: {ios_in_progress}"}
    - cpu:
        poll-interval: 1000
        content:
          map:
            conditions:
              id == 5:
                - string: {text: " {id}", foreground: *primary}
                - string: {text: "{cpu}%"}
              id < 0:
                - string: {text: " ", foreground: *primary}
                - string: {text: "{cpu}% "}
              id > 0:
                - string: {text: " {id}", foreground: *primary}
                - string: {text: "{cpu}% "}
    - mem:
        poll-interval: 1000
        content:
          - string: {text: " ", foreground: *primary}
          - string: {text: "{used:mb} MB / {total:gb} GB ({free:gb} GB)"}
    - network:
        poll-interval: 5000
        content:
          map:
            conditions:
              name == "wlp1s0" && state == "up":
                - string: {text: "󰖩 ", foreground: *primary}
                - string: {text: "{ssid} {quality}% DL {dl-speed} UL {ul-speed}"}
              name == "wlp1s0":
                - string: {text: "󰖩 ", foreground: *primary}
                - string: {text: "{state}"}
    - pipewire:
        content:
          map:
            conditions:
              type == "sink":
                - string: {text: " ", foreground: *primary}
                - string: {text: "{form_factor}"}
                - map:
                    conditions:
                      ~muted:
                        string: {text: "{cubic_volume}%"}
                      muted:
                        string: {text: "mute"}
    - backlight:
        name: amdgpu_bl1
        content:
          - string: {text: "󰃠 ", foreground: *primary}
          - string: {text: "{percent}%"}
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          - string: {text: " ", foreground: *primary}
          - string: {text: "{state} ({estimate}) {capacity}%"}
    - clock:
        date-format: "%Y.%m.%d"
        content:
          - string: {text: " ", foreground: *primary}
          - string: {text: "{date}"}
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "󰥔 ", foreground: *primary}
          - string: {text: "{time}"}
