#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config click_to_focus none
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor true

bspc config border_width 3
bspc config window_gap 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color #181825
bspc config active_border_color #181825
bspc config focused_border_color #F5C2E7
