#!/bin/bash

SESSION_NAME="kanban_board_run"
DIRECTORY=~/University/Harmadik-felev/AFP1/kanban_board/

sudo systemctl start mariadb;
sudo systemctl start docker;
tmux new-session -d -s $SESSION_NAME -c $DIRECTORY -n backend "cd backend && php artisan serve";
tmux new-window -t $SESSION_NAME -n frontend;
tmux send -t $SESSION_NAME:frontend "cd frontend && npm start" ENTER;
tmux new-window -t $SESSION_NAME -n docker;
tmux send -t $SESSION_NAME:docker "sudo docker run -p 6001:6001 quay.io/soketi/soketi:1.0-16-distroless" ENTER;
tmux a -t $SESSION_NAME:docker
